# Generated by Django 5.2.9 on 2025-12-18 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancerecord',
            name='qr_data',
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='qr_payload',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(choices=[('ON_TIME', 'On time'), ('LATE', 'Late'), ('EARLY', 'Early'), ('INVALID_QR', 'Invalid QR'), ('MISSING', 'Missing')], default='ON_TIME', max_length=20),
        ),
    ]
