# Generated by Django 5.2.9 on 2025-12-19 12:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guards', '0002_remove_attendancerecord_qr_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardprofile',
            name='last_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guardprofile',
            name='last_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guardprofile',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guardprofile',
            name='status',
            field=models.CharField(choices=[('on_patrol', 'On Patrol'), ('on_break', 'On Break'), ('off_duty', 'Off Duty'), ('on_site', 'On Site')], default='off_duty', max_length=32),
        ),
        migrations.AddField(
            model_name='patrolcoordinate',
            name='accuracy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Checkpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('premise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='guards.premise')),
            ],
        ),
        migrations.CreateModel(
            name='CheckpointLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('checkpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guards.checkpoint')),
                ('guard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guards.shift')),
            ],
            options={
                'unique_together': {('checkpoint', 'shift', 'guard')},
            },
        ),
    ]
