# Generated by Django 5.2.9 on 2025-12-20 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guards', '0003_guardprofile_last_lat_guardprofile_last_lng_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='assigned_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp assigned_guard was set', null=True),
        ),
    ]
